package com.example.stpos.Util;

public interface Constant {

    String MY_TOKEN_ID="MY_TOKEN_ID";
    String TOKEN="TOKEN";
    String IMAGEURL="https://bfdcapps.com/images/";
    ///image id
    int PICK_PHOTO_ONE=101;
    int PICK_PHOTO_TWO=102;
    int PICK_PHOTO_THREE=103;
    int PICK_PHOTO_FOUR=104;
    String PRODUCTID="PRODUCTID";

    String CATEGORYNAME="CATEGORYNAME";
    String CATEGORYID="CATEGORYID";

    String SUBCATEGORYID="SUBCATEGORYID";

    String CELL_NO="CELL NO";
    String ADDRESS="ADDRESS";
    String ID="ID";
    String COMPANY_NAME="COMPANY NAME";

    String ACTIONBAR_TITLE="ACTIONBAR_TITLE";

//FOR PRODUT GRIDVIEW

    String TYPE="TYPE";
    String TYPEPRODUCT="TYPEPRODUCT";
    String TYPEPRODUCTID="TYPEPRODUCTID";

    String CATID="CATID";


//    String RECOMMENDED="RECOMMENDED";
//    String TOPSELLER="TOPSELLER";
//    String SPECIAL="SPECIAL";
//    String NEWARRIVALS="NEWARRIVALS";
//    String HOTDEALS="HOTDEALS";
//    String BESTSELLER="BESTSELLER";
//    String TOPREVIEWALL="TOPREVIEWALL";


    int PLUS=0;
    int MINUSE=1;

//customer=================
    String NAME="NAME";
    String PHONE="PHONE";
    String CUSTOMERID="MERCENTID";


    //Order details
    String ORDERID="ORDERID";
    String ORDERINVOICEID="ORDERINVOICEID";
    String ORDERSTATUS="ORDERSTATUS";
    String ORDERSUBTOTALAMOUNT="ORDERSUBTOTALAMOUNT";
    String ORDERTOTALAMOUNT="ORDERTOTALAMOUNT";
    String ORDERPAYMENTTYPE="ORDERPAYMENTTYPE";
    String ORDERDISCOUNT="ORDERDISCOUNT";
    String ORDERPAIDSTATUS="ORDERPAIDSTATUS";

    //address
    String ADDRESSID="ADDRESSID";
    String ADDRESSNAME="ADDRESSNAME";
    String ADDRESSPHONE="ADDRESSPHONE";
    String ADDRESSADDRESS="ADDRESSADDRESS";
    String ADDRESSHOMEOROFFICE="ADDRESSHOMEOROFFICE";
    String ADDRESSDELIVERY="ADDRESSDELIVERY";
    String ADDRESSTITLE="ADDRESSTITLE";
    String ADDRESSTYPE="ADDRESSTYPE";

    String ADDRESSRECEIVERNAME="ADDRESSRECEIVERNAME";
    String ADDRESSPHONENUMBER="ADDRESSPHONENUMBER";
    String ADDRESSSALESCENTERID="ADDRESSSALESCENTERID";




    //search

    String SEARCH_WORD="SEARCH_WORD";

//cartForDirectchk
    String FROMDIRECT="FROMDIRECT";
    String CARTIDFORDIRECT="CARTIDFORDIRECT";

    //
    String NOTICEID="NOTICEID";

    String PRODUCTHALFPRICE="PRODUCTPRICE";


}
